#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

source ./.husky/run_check.sh
source ./.husky/get_time.sh

run_all_checks() {
	# TODO: Run in parallel?
	# TODO: Log time for each task
	run_check "Checking for type errors" "npx tsc --noEmit" 
	run_check "Checking for linting problems" "npm run lint"
	run_check "Running unit tests" "npm run coverage"
}

clear

# Prevents husky default behaviour
set +e

echo
echo "⚙️   Starting pre-commit checks"
echo

get_time run_all_checks

echo
echo "🎉  All checks passed. Commiting changes! ($time_to_run)"
echo