#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

source ./.husky/run_check.sh
source ./.husky/get_time.sh

clear

run_all_checks() {
	# TODO: Run in parallel?
	# TODO: Log time for each task

	run_check "Checking for type errors" "npx tsc --noEmit" 
	run_check "Checking for linting problems" "npm run lint"
	run_check "Running unit tests" "npm run coverage"
	# TODO: npm ci constantly has errors (discover why)
	run_check "Installing dependencies" "npm ci"
	run_check "Building application" "npm run build"
	# TODO: Start application?
}

# Prevents husky default behaviour
set +e

echo
echo "⚙️   Starting pre-push checks"
echo

get_time run_all_checks

echo
echo "🎉  All checks passed. Commiting changes! ($time_to_run)"
echo